# Generated by Django 4.1.3 on 2022-12-13 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('date_of_membership', models.DateField(auto_now_add=True)),
                ('date_of_birth', models.DateField()),
                ('mobile', models.CharField(blank=True, max_length=10)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('palce_of_resident', models.CharField(max_length=150)),
                ('occupation', models.CharField(max_length=150)),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Separated', 'Separated')], max_length=10)),
                ('name_of_spouse', models.CharField(blank=True, max_length=150, null=True)),
                ('number_of_children', models.CharField(blank=True, max_length=2, null=True)),
                ('is_baptized', models.BooleanField(default=False, verbose_name='Have you been baptisez?')),
                ('wheer_to_serve', models.CharField(choices=[('Ushering', 'Ushering'), ('Music', 'Music'), ('Envagelism', 'Envagelism'), ('Prayer', 'Prayer'), ('Media', 'Media')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('date_of_first_visit', models.DateField(auto_now_add=True)),
                ('is_confessed_jesus', models.BooleanField(default=False, help_text='Have you COnfessed Jesus Christ as your Lord and personl savior?', verbose_name='Confessed Jesus Christ?')),
                ('mobile', models.CharField(blank=True, max_length=10)),
                ('palce_of_resident', models.CharField(max_length=150)),
                ('invited_by', models.CharField(max_length=150)),
                ('current_place_of_fellowship', models.CharField(max_length=255)),
                ('wish_to_be_a_member', models.CharField(choices=[('yes', 'Yes'), ('just_visiting', 'Just Visiting'), ('still_considering', 'Still considering')], max_length=30)),
                ('prayer_request', models.TextField(blank=True)),
            ],
        ),
    ]
